# 开发环境服务
# 王海兵 2023-03-15

version: "3.9"

volumes:
  app_mysql_data:
  app_redis_data:

services:
  nginx:
    image: nginx
    container_name: ${APP_NAME}_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - php-fpm

  php-fpm:
    image: ${APP_NAME}_php-fpm
    build: ./php-fpm
    container_name: ${APP_NAME}_php-fpm
    restart: always
    volumes:
      - ./backend:/var/www/html
      - ./php-fpm/php.production.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
      - rabbitMQ

  supervisor:
    image: ${APP_NAME}_supervisor
    build: ./supervisor
    container_name: ${APP_NAME}_supervisor
    restart: always
    volumes:
      - ./backend:/var/www/html
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
      - ./supervisor/supervisor.d:/etc/supervisor.d
    ports:
      - ${SUPERVISOR_PORT}:9001
        
  mysql:
    image: mysql
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app_mysql_data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --default-time-zone=+08:00 # 设置时区
      - --slow_query_log=ON # 启用慢查询日志
      - --long_query_time=0.5 # 慢查询日志记录的阀值：500 ms
      - --log_queries_not_using_indexes=ON # 慢查询记录未使用索引的记录
      - --slow_query_log_file=/var/log/mysql/slow.log # 慢查询的文件名

  phpMyAdmin:
    image: phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    restart: always
    container_name: ${APP_NAME}_redis
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - app_redis_data:/data

  rabbitMQ:
    image: rabbitmq:3.11.10-management-alpine
    restart: always
    hostname: ${APP_NAME}_rabbitmq
    container_name: ${APP_NAME}_rabbitmq
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}